### ISSUE TITLE
In the tests, c2mop:direct-slot-definition-class is defined with &key rather than &rest

### ISSUE THREAD

**Issue by Yehouda** [Hexstream/class-options#1]
In tests/tests.lisp, there are several definitions of methods for **c2mop:direct-slot-definition-class**, all of them with **&key** in the lambda list. This is wrong, because the lambda list of  **c2mop:direct-slot-definition-class** is `(class &rest initargs)` https://clos-mop.hexstreamsoft.com/generic-functions-and-methods/. 

With the &key, it means it doesn't allow any keys, so gives an error when the implemtation actually checks (because at least the name is in the initargs).

**Comment by Hexstream** [comment]
(Wow, [LispWorks](https://github.com/Yehouda)?! Nice! ;))

Thank you for the report. Unfortunately, you are correct. I had incorrectly assumed that the [c2mop:direct-slot-definition-class](https://clos-mop.hexstreamsoft.com/generic-functions-and-methods/#direct-slot-definition-class) generic function specifies `&key &allow-other-keys`. Frankly, I think this should have been the case, or alternatively, the primary method specialized on `standard-class` could specify [`&key name initform initfunction type allocation initargs readers writers documentation`](https://clos-mop.hexstreamsoft.com/generic-functions-and-methods/#initialization-of-slot-definition-metaobjects_initargs). (Thoughts, @pcostanza?) My code would have been correct in either of those cases according to [CLHS 7.6.4 Congruent Lambda-lists for all Methods of a Generic Function](http://www.lispworks.com/documentation/HyperSpec/Body/07_fd.htm) and [CLHS 7.6.5 Keyword Arguments in Generic Functions and Methods](http://www.lispworks.com/documentation/HyperSpec/Body/07_fe.htm).

I will perform a full review of my ready-to-use libraries with respect to this issue and issue new releases where appropriate. I expect to do this today, or otherwise very soon. I'll let you know when this is done.

(I should probably also start testing on LispWorks eventually, but I'm extremely busy and I have a deadline coming up...)

**Comment by Hexstream** [comment]
Alright, this is fixed in class-options 1.0.1. It turns out that none of my other libraries were affected, after all.

Here is the [updated tarball](https://tarballs.hexstreamsoft.com/libraries/latest/class-options_latest.tar.gz). (Beware of caching issues. The new tarball has `class-options_1.0.1` as top-level directory.)

I'm actually pretty livid that the CLOS MOP specification does not define the [c2mop:direct-slot-definition-class](https://clos-mop.hexstreamsoft.com/generic-functions-and-methods/#direct-slot-definition-class) and related generic functions as specifying `&key &allow-other-keys`, but whatever.

(**edit:** [Tweeted.](https://twitter.com/HexstreamSoft/status/1315707536088207362))

**Comment by ghost** [comment]
The CLOS MOP specification as we know it today is not a finished specification. There are a lot of these little omissions that, if there had been some proper standardization process around it, would have probably been caught. Alas, this is what we have to live with.

**Comment by Hexstream** [comment]
Thank you. I am still pretty solidly satisfied with the CLOS MOP specification. It is a GEM!

(Also, this could easily be fixed in a library.)
